#
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#
extra-y = nand_read.o
obj-y	:= mini2440.o
extra-y	+= lowlevel_init.o
obj-$(CONFIG_MINI2440_FB)+=mini2440_fb.o
